### ISSUE TITLE
tagging fails

### ISSUE THREAD

**Issue by cpan-mila** [robhammond/bkmrx.com#3]
when i try to add a tag to an bookmark this does not work. in the log i get: 

ElasticsearchIllegalArgumentException[failed to execute script]; nested: ScriptException[scripts of type [inline], operation [update] and lang [groovy] are disabled]; , called from sub Search::Elasticsearch::Role::Client::Direct::__ANON__ at /home/mila/Projects/Software/OpenShift/bkmrx/bkmrx.com/script/../lib/BkxMojo/Ajax.pm line 480. With vars: {'status_code' => 400,'body' => {'status' => 400,'error' => 'ElasticsearchIllegalArgumentException[failed to execute script]; nested: ScriptException[scripts of type [inline], operation [update] and lang [groovy] are disabled]; '},'request' => {'method' => 'POST','mime_type' => 'application/json','body' => {'script' => 'if (!ctx._source.tags.contains(tag)) {ctx._source.tags += tag} else {ctx.op = "none"}','params' => {'tag' => 'dddddd'}},'qs' => {'parent' => '96e7ce197da22d57c8c308c14a548c4d11005019'},'serialize' => 'std','path' => '/bkmrx/bookmark/072d0c6b0dd9cb636615355030790a0e220fa1c2/_update','ignore' => []}}

adding a description results in:

DocumentMissingException[[bkmrx][4] [bookmark][072d0c6b0dd9cb636615355030790a0e220fa1c2]: document missing], called from sub Search::Elasticsearch::Role::Client::Direct::__ANON__ at /home/mila/Projects/Software/OpenShift/bkmrx/bkmrx.com/script/../lib/BkxMojo/Crud.pm line 350. With vars: {'body' => {'status' => 404,'error' => 'DocumentMissingException[[bkmrx][4] [bookmark][072d0c6b0dd9cb636615355030790a0e220fa1c2]: document missing]'},'status_code' => 404,'request' => {'ignore' => [],'serialize' => 'std','path' => '/bkmrx/bookmark/072d0c6b0dd9cb636615355030790a0e220fa1c2/_update','qs' => {'parent' => '072d0c6b0dd9cb636615355030790a0e220fa1c2'},'mime_type' => 'application/json','body' => {'script' => 'ctx._source.user_description = page_desc','params' => {'page_desc' => 'sssssssss'}},'method' => 'POST'}}

**Comment by robhammond** [comment]
Hmm which version of ElasticSearch are you running? This function uses scripting features that were disabled in v1.3 I think and I haven't had time to update the functions

Have clarified install instructions on version required.

**Comment by cpan-mila** [comment]
ok, thanks. i used 1.7.1.

**Comment by robhammond** [comment]
You can read more about the issue here: https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-scripting.html

It is possible to switch scripting back on I believe even in later versions
