### ISSUE TITLE
Backup

### ISSUE THREAD

**Issue by pydubreucq** [robhammond/bkmrx.com#4]
Hi,
I saw the bkmrx.com website and I have a question about backup.
You said :
"save your links in an industry compatible format"
What is the format ?
Thanks by advance
Best Regards
Pierre-Yves

**Comment by robhammond** [comment]
Hi Pierre-Yves,

Thanks for the interest and good question - it's an HTML export in the old netscape format that is used by Delicious.com and browsers including Firefox & Chrome

Thanks
Rob
